version: '3.9'

services:
  raspberry_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intelligent-heater
    volumes:
      - .:/app 
      - ./logs:/app/logs
      - .env:/app/.env
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    restart: unless-stopped
    env_file:
      - .env
    privileged: true